"""initial_baseline_all_models

Revision ID: 2699e47c4e1b
Revises: 
Create Date: 2026-04-05 17:46:53.377337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2699e47c4e1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidr_route_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('normalized_cidr', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('route_target', sa.Enum('RU', 'DE', 'DIRECT', 'DEFAULT', name='routetarget'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_cidr', name='uq_cidr_route_rules_normalized_cidr')
    )
    op.create_index(op.f('ix_cidr_route_rules_cidr'), 'cidr_route_rules', ['cidr'], unique=False)
    op.create_index(op.f('ix_cidr_route_rules_is_active'), 'cidr_route_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_cidr_route_rules_normalized_cidr'), 'cidr_route_rules', ['normalized_cidr'], unique=False)
    op.create_index(op.f('ix_cidr_route_rules_priority'), 'cidr_route_rules', ['priority'], unique=False)
    op.create_table('custom_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('route_type', sa.Enum('DIRECT', 'VPN', name='routetype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_routes_address'), 'custom_routes', ['address'], unique=False)
    op.create_table('domain_route_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_domain', sqlmodel.sql.sqltypes.AutoString(length=253), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'WILDCARD', name='domainmatchtype'), nullable=False),
    sa.Column('route_target', sa.Enum('RU', 'DE', 'DIRECT', 'DEFAULT', name='routetarget'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_domain', 'match_type', name='uq_domain_route_rules_normalized_domain_match_type')
    )
    op.create_index(op.f('ix_domain_route_rules_domain'), 'domain_route_rules', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_route_rules_is_active'), 'domain_route_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_domain_route_rules_normalized_domain'), 'domain_route_rules', ['normalized_domain'], unique=False)
    op.create_index(op.f('ix_domain_route_rules_priority'), 'domain_route_rules', ['priority'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('features', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('vpn_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('private_key_enc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_entry_node', sa.Boolean(), nullable=False),
    sa.Column('is_exit_node', sa.Boolean(), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('current_clients', sa.Integer(), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_key')
    )
    op.create_table('vpn_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('private_key_enc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('subnet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_entry_node', sa.Boolean(), nullable=False),
    sa.Column('is_exit_node', sa.Boolean(), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('current_clients', sa.Integer(), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_key')
    )
    op.create_table('referral_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('bonus_earned_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_codes_code'), 'referral_codes', ['code'], unique=True)
    op.create_index(op.f('ix_referral_codes_user_id'), 'referral_codes', ['user_id'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('bonus_given', sa.Boolean(), nullable=False),
    sa.Column('bonus_days', sa.Integer(), nullable=False),
    sa.Column('first_payment_at', sa.DateTime(), nullable=True),
    sa.Column('first_payment_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELED', name='subscriptionstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('is_complimentary', sa.Boolean(), nullable=False),
    sa.Column('access_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_payment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'BLOCKED', 'REPLACED', name='devicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_handshake_at', sa.DateTime(), nullable=True),
    sa.Column('last_endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('block_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_device_key'), 'user_devices', ['device_key'], unique=True)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('vpn_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entry_node_id', sa.Integer(), nullable=False),
    sa.Column('exit_node_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('current_clients', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_node_id'], ['vpn_nodes.id'], ),
    sa.ForeignKeyConstraint(['exit_node_id'], ['vpn_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vpn_routes_entry_node_id'), 'vpn_routes', ['entry_node_id'], unique=False)
    op.create_index(op.f('ix_vpn_routes_exit_node_id'), 'vpn_routes', ['exit_node_id'], unique=False)
    op.create_table('device_security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('DEVICE_CREATED', 'MIGRATED_PRIMARY_DEVICE', 'CONFIG_ROTATED', 'DEVICE_REVOKED', 'DEVICE_BLOCKED', 'DEVICE_UNBLOCKED', 'SUSPICIOUS_ENDPOINT_CHURN', 'CONCURRENT_HANDSHAKE_SUSPECTED', name='devicesecurityeventtype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='deviceeventseverity'), nullable=False),
    sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_security_events_device_id'), 'device_security_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_security_events_user_id'), 'device_security_events', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('provider', sa.Enum('YOOKASSA', 'TINKOFF', 'MANUAL', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payment_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('payment_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('vpn_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('entry_node_id', sa.Integer(), nullable=True),
    sa.Column('exit_node_id', sa.Integer(), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('private_key_enc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_upload_bytes', sa.Integer(), nullable=False),
    sa.Column('total_download_bytes', sa.Integer(), nullable=False),
    sa.Column('last_handshake_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ),
    sa.ForeignKeyConstraint(['entry_node_id'], ['vpn_nodes.id'], ),
    sa.ForeignKeyConstraint(['exit_node_id'], ['vpn_nodes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['vpn_routes.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['vpn_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('public_key')
    )
    op.create_index(op.f('ix_vpn_clients_device_id'), 'vpn_clients', ['device_id'], unique=True)
    op.create_index(op.f('ix_vpn_clients_entry_node_id'), 'vpn_clients', ['entry_node_id'], unique=False)
    op.create_index(op.f('ix_vpn_clients_exit_node_id'), 'vpn_clients', ['exit_node_id'], unique=False)
    op.create_index(op.f('ix_vpn_clients_route_id'), 'vpn_clients', ['route_id'], unique=False)
    op.create_index(op.f('ix_vpn_clients_server_id'), 'vpn_clients', ['server_id'], unique=False)
    op.create_index(op.f('ix_vpn_clients_user_id'), 'vpn_clients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_clients_user_id'), table_name='vpn_clients')
    op.drop_index(op.f('ix_vpn_clients_server_id'), table_name='vpn_clients')
    op.drop_index(op.f('ix_vpn_clients_route_id'), table_name='vpn_clients')
    op.drop_index(op.f('ix_vpn_clients_exit_node_id'), table_name='vpn_clients')
    op.drop_index(op.f('ix_vpn_clients_entry_node_id'), table_name='vpn_clients')
    op.drop_index(op.f('ix_vpn_clients_device_id'), table_name='vpn_clients')
    op.drop_table('vpn_clients')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_device_security_events_user_id'), table_name='device_security_events')
    op.drop_index(op.f('ix_device_security_events_device_id'), table_name='device_security_events')
    op.drop_table('device_security_events')
    op.drop_index(op.f('ix_vpn_routes_exit_node_id'), table_name='vpn_routes')
    op.drop_index(op.f('ix_vpn_routes_entry_node_id'), table_name='vpn_routes')
    op.drop_table('vpn_routes')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_key'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_codes_user_id'), table_name='referral_codes')
    op.drop_index(op.f('ix_referral_codes_code'), table_name='referral_codes')
    op.drop_table('referral_codes')
    op.drop_table('vpn_servers')
    op.drop_table('vpn_nodes')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_index(op.f('ix_domain_route_rules_priority'), table_name='domain_route_rules')
    op.drop_index(op.f('ix_domain_route_rules_normalized_domain'), table_name='domain_route_rules')
    op.drop_index(op.f('ix_domain_route_rules_is_active'), table_name='domain_route_rules')
    op.drop_index(op.f('ix_domain_route_rules_domain'), table_name='domain_route_rules')
    op.drop_table('domain_route_rules')
    op.drop_index(op.f('ix_custom_routes_address'), table_name='custom_routes')
    op.drop_table('custom_routes')
    op.drop_index(op.f('ix_cidr_route_rules_priority'), table_name='cidr_route_rules')
    op.drop_index(op.f('ix_cidr_route_rules_normalized_cidr'), table_name='cidr_route_rules')
    op.drop_index(op.f('ix_cidr_route_rules_is_active'), table_name='cidr_route_rules')
    op.drop_index(op.f('ix_cidr_route_rules_cidr'), table_name='cidr_route_rules')
    op.drop_table('cidr_route_rules')
    # ### end Alembic commands ###
